package com.ssh.shuoshi.greendao.local;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ssh.shuoshi.greendao.ServiceTicket;

import com.ssh.shuoshi.greendao.local.ServiceTicketDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig serviceTicketDaoConfig;

    private final ServiceTicketDao serviceTicketDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        serviceTicketDaoConfig = daoConfigMap.get(ServiceTicketDao.class).clone();
        serviceTicketDaoConfig.initIdentityScope(type);

        serviceTicketDao = new ServiceTicketDao(serviceTicketDaoConfig, this);

        registerDao(ServiceTicket.class, serviceTicketDao);
    }
    
    public void clear() {
        serviceTicketDaoConfig.clearIdentityScope();
    }

    public ServiceTicketDao getServiceTicketDao() {
        return serviceTicketDao;
    }

}
